model: convnext_tiny
model_family: convnext
dataset: cifar10
task: classification
epochs: 10
batch_size: 64
optimizer: adam
lr: 0.01  # Lower LR can help with modern models
scheduler: null
pretrained: true
transfer_learning: false