model: efficientnet_v2_s
model_family: efficientnetv2
dataset: cifar10
task: classification
epochs: 10
batch_size: 64
optimizer: adam
lr: 0.01
scheduler: null
pretrained: true
transfer_learning: false