model: efficientnet_b0
model_family: efficientnet_32_input
dataset: face
task: disease
epochs: 100
batch_size: 64
optimizer: adam
lr: 0.001
scheduler: null
pretrained: false
transfer_learning: false
resize: 32