model: efficientnet_v2_s
model_family: efficientnetv2
dataset: cifar10
task: classification
epochs: 1
batch_size: 64
optimizer: adam
lr: 0.001
scheduler: null
pretrained: false
transfer_learning: true