model: vit_b_16
model_family: vit
dataset: cifar10
task: classification
epochs: 10
batch_size: 64
optimizer: adam
lr: 0.01  # Lower LR often works better for transformers
scheduler: null
pretrained: false
transfer_learning: false